// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdjcovxzvjcvocxjzjkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkamNvdnh6dmpjdm9jeGp6amtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMzQ0NTksImV4cCI6MjA3NDgxMDQ1OX0.9TCoQ29Kg68udOd3woFBOk5jQlgOaaXkAHnlE05G_6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});